import { SiteState, ProcessStage } from "./constants";

import { Category } from "@/models/category";
import { Site } from "@/models/site";

export const SEED_CATEGORIES: Category[] = [
  // === AI对话 ===
  { _id: "cat-ai-chat", icon: "💬", name: "AI对话", parent: undefined, featured: true, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-chat-general", icon: "🤖", name: "通用对话", parent: "cat-ai-chat", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-chat-cn", icon: "🇨🇳", name: "国产对话", parent: "cat-ai-chat", featured: false, weight: 90, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI编程 ===
  { _id: "cat-ai-programming", icon: "💻", name: "AI编程", parent: undefined, featured: true, weight: 95, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-code-assistant", icon: "🧠", name: "代码助手", parent: "cat-ai-programming", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-code-ide", icon: "🛠", name: "AI IDE", parent: "cat-ai-programming", featured: false, weight: 90, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-code-gen", icon: "🚀", name: "应用生成", parent: "cat-ai-programming", featured: false, weight: 80, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI写作 ===
  { _id: "cat-ai-writing", icon: "✏️", name: "AI写作", parent: undefined, featured: true, weight: 90, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-write-general", icon: "📝", name: "通用写作", parent: "cat-ai-writing", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-write-en", icon: "🇬🇧", name: "英文润色", parent: "cat-ai-writing", featured: false, weight: 90, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI制图 ===
  { _id: "cat-ai-image", icon: "🎨", name: "AI制图", parent: undefined, featured: true, weight: 85, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-image-gen", icon: "🖼", name: "图像生成", parent: "cat-ai-image", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-image-design", icon: "📐", name: "设计工具", parent: "cat-ai-image", featured: false, weight: 90, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI视频 ===
  { _id: "cat-ai-video", icon: "🎬", name: "AI视频", parent: undefined, featured: true, weight: 80, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-video-gen", icon: "📽", name: "视频生成", parent: "cat-ai-video", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-video-edit", icon: "✂️", name: "视频编辑", parent: "cat-ai-video", featured: false, weight: 90, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI音乐 ===
  { _id: "cat-ai-music", icon: "🎵", name: "AI音乐", parent: undefined, featured: true, weight: 75, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-music-gen", icon: "🎧", name: "音乐生成", parent: "cat-ai-music", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI搜索 ===
  { _id: "cat-ai-search", icon: "🔍", name: "AI搜索", parent: undefined, featured: true, weight: 70, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI教育 ===
  { _id: "cat-ai-education", icon: "📚", name: "AI教育", parent: undefined, featured: true, weight: 65, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-edu-tutor", icon: "👨‍🏫", name: "AI辅导", parent: "cat-ai-education", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-edu-tools", icon: "📖", name: "学习工具", parent: "cat-ai-education", featured: false, weight: 90, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI办公 ===
  { _id: "cat-ai-office", icon: "💼", name: "AI办公", parent: undefined, featured: true, weight: 60, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-office-ppt", icon: "📊", name: "演示文档", parent: "cat-ai-office", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-office-doc", icon: "📄", name: "文档处理", parent: "cat-ai-office", featured: false, weight: 90, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI自动化 ===
  { _id: "cat-ai-auto", icon: "🤖", name: "AI自动化", parent: undefined, featured: true, weight: 55, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-auto-flow", icon: "🔄", name: "工作流自动化", parent: "cat-ai-auto", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI赚钱 ===
  { _id: "cat-ai-money", icon: "💰", name: "AI赚钱", parent: undefined, featured: true, weight: 50, createdAt: Date.now(), updatedAt: Date.now() },
  { _id: "sub-money-marketing", icon: "📢", name: "销售营销", parent: "cat-ai-money", featured: false, weight: 100, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI数据分析 ===
  { _id: "cat-ai-data-analysis", icon: "📊", name: "AI数据分析", parent: undefined, featured: true, weight: 45, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI助手 ===
  { _id: "cat-ai-agent", icon: "🧑‍💻", name: "AI助手", parent: undefined, featured: true, weight: 42, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI翻译 ===
  { _id: "cat-ai-translate", icon: "🌍", name: "AI翻译", parent: undefined, featured: true, weight: 40, createdAt: Date.now(), updatedAt: Date.now() },
  // === AI目录导航 ===
  { _id: "cat-ai-directories", icon: "📃", name: "AI目录导航", parent: undefined, featured: true, weight: 35, createdAt: Date.now(), updatedAt: Date.now() },
];

const now = Date.now();

export const SEED_SITES: Site[] = [
  {
    _id: "site-chatgpt",
    userId: "00000000000000000",
    siteKey: "chatgpt",
    url: "https://chat.openai.com",
    name: "ChatGPT",
    icon: "logos:openai-icon",
    subCategory: "通用对话",
    featured: true,
    weight: 100,
    snapshot: "https://placehold.co/640x360/FF6B35/FFFFFF?text=ChatGPT",
    description:
      "OpenAI 推出的对话式 AI，可用于内容创作、客服、编程辅助，是 AI 副业入门必备工具。",
    pricingType: "免费/付费",
    categories: ["AI写作", "AI赚钱"],
    images: [],
    features: ["智能对话", "代码生成", "多语言支持", "插件生态"],
    usecases: ["自媒体写作", "客服自动化", "编程辅助", "知识问答"],
    users: ["自媒体人", "程序员", "创业者"],
    relatedSearches: ["GPT-4", "AI对话", "OpenAI"],
    pricings: ["免费版", "Plus $20/月"],
    links: {},
    voteCount: 1280,
    metaKeywords: ["ChatGPT", "AI写作", "OpenAI"],
    metaDescription: "ChatGPT - 最受欢迎的 AI 对话工具",
    searchSuggestWords: ["chatgpt", "gpt", "openai"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-midjourney",
    userId: "00000000000000000",
    siteKey: "midjourney",
    url: "https://www.midjourney.com",
    name: "Midjourney",
    icon: "simple-icons:midjourney",
    subCategory: "艺术创作",
    featured: true,
    weight: 99,
    snapshot: "https://placehold.co/640x360/7B2FBE/FFFFFF?text=Midjourney",
    description:
      "顶级 AI 绘图工具，通过文字描述生成高质量艺术图片，适合设计副业和电商素材制作。",
    pricingType: "付费",
    categories: ["AI绘图", "AI赚钱"],
    images: [],
    features: ["文字生图", "风格多样", "高清输出", "社区分享"],
    usecases: ["电商主图", "自媒体封面", "品牌设计", "插画创作"],
    users: ["设计师", "电商卖家", "自媒体人"],
    relatedSearches: ["AI绘画", "文生图"],
    pricings: ["Basic $10/月", "Standard $30/月"],
    links: {},
    voteCount: 960,
    metaKeywords: ["Midjourney", "AI绘图", "AI绘画"],
    metaDescription: "Midjourney - 最强 AI 绘图工具",
    searchSuggestWords: ["midjourney", "mj", "ai绘画"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-runway",
    userId: "00000000000000000",
    siteKey: "runway",
    url: "https://runwayml.com",
    name: "Runway",
    icon: "logos:runwayml",
    subCategory: "文生视频",
    featured: true,
    weight: 98,
    snapshot: "https://placehold.co/640x360/1A1A2E/FFFFFF?text=Runway",
    description:
      "专业 AI 视频生成平台，支持文生视频、图生视频，是短视频创作者和广告制作的利器。",
    pricingType: "免费/付费",
    categories: ["AI视频", "AI赚钱"],
    images: [],
    features: ["文生视频", "图生视频", "视频编辑", "AI特效"],
    usecases: ["短视频制作", "广告创意", "产品展示", "社交媒体"],
    users: ["短视频博主", "广告从业者", "内容创作者"],
    relatedSearches: ["AI视频", "文生视频"],
    pricings: ["免费版", "Standard $15/月"],
    links: {},
    voteCount: 820,
    metaKeywords: ["Runway", "AI视频", "文生视频"],
    metaDescription: "Runway - AI 视频生成平台",
    searchSuggestWords: ["runway", "ai视频"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-canva",
    userId: "00000000000000000",
    siteKey: "canva",
    url: "https://www.canva.com",
    name: "Canva",
    icon: "logos:canva",
    subCategory: "在线设计",
    featured: true,
    weight: 97,
    snapshot: "https://placehold.co/640x360/00C4CC/FFFFFF?text=Canva",
    description:
      "集成 AI 功能的在线设计平台，可快速制作海报、PPT、社交媒体图片，适合非设计师快速出图。",
    pricingType: "免费/付费",
    categories: ["AI绘图", "AI办公"],
    images: [],
    features: ["AI设计", "模板丰富", "团队协作", "一键导出"],
    usecases: ["海报设计", "PPT制作", "社交媒体", "品牌物料"],
    users: ["自媒体人", "小企业主", "运营人员"],
    relatedSearches: ["在线设计", "AI设计"],
    pricings: ["免费版", "Pro $12.99/月"],
    links: {},
    voteCount: 750,
    metaKeywords: ["Canva", "AI设计", "在线设计"],
    metaDescription: "Canva - AI 在线设计工具",
    searchSuggestWords: ["canva", "设计"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-notion-ai",
    userId: "00000000000000000",
    siteKey: "notion-ai",
    url: "https://www.notion.so/product/ai",
    name: "Notion AI",
    icon: "logos:notion-icon",
    subCategory: "智能笔记",
    featured: true,
    weight: 96,
    snapshot: "https://placehold.co/640x360/000000/FFFFFF?text=Notion+AI",
    description:
      "Notion 内置 AI 助手，可辅助写作、总结、翻译和头脑风暴，提升知识管理和内容创作效率。",
    pricingType: "付费",
    categories: ["AI写作", "AI办公"],
    images: [],
    features: ["AI写作", "内容总结", "翻译", "头脑风暴"],
    usecases: ["笔记整理", "文档写作", "项目管理", "知识库"],
    users: ["知识工作者", "学生", "创业者"],
    relatedSearches: ["Notion", "AI笔记"],
    pricings: ["$10/月"],
    links: {},
    voteCount: 680,
    metaKeywords: ["Notion AI", "AI写作", "AI办公"],
    metaDescription: "Notion AI - 智能笔记助手",
    searchSuggestWords: ["notion", "notion ai"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-elevenlabs",
    userId: "00000000000000000",
    siteKey: "elevenlabs",
    url: "https://elevenlabs.io",
    name: "ElevenLabs",
    icon: "logos:elevenlabs",
    subCategory: "语音合成",
    featured: true,
    weight: 95,
    snapshot: "https://placehold.co/640x360/6366F1/FFFFFF?text=ElevenLabs",
    description:
      "领先的 AI 语音合成平台，可生成逼真的人声配音，适合有声书、播客和短视频配音副业。",
    pricingType: "免费/付费",
    categories: ["AI视频", "AI赚钱"],
    images: [],
    features: ["语音克隆", "多语言配音", "情感表达", "API接口"],
    usecases: ["短视频配音", "有声书", "播客制作", "广告配音"],
    users: ["短视频博主", "播客主", "内容创作者"],
    relatedSearches: ["AI配音", "语音合成"],
    pricings: ["免费版", "Starter $5/月"],
    links: {},
    voteCount: 620,
    metaKeywords: ["ElevenLabs", "AI配音", "语音合成"],
    metaDescription: "ElevenLabs - AI 语音合成工具",
    searchSuggestWords: ["elevenlabs", "ai配音"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-cursor",
    userId: "00000000000000000",
    siteKey: "cursor",
    url: "https://cursor.com",
    name: "Cursor",
    icon: "logos:cursor",
    subCategory: "代码编辑器",
    featured: true,
    weight: 94,
    snapshot: "https://placehold.co/640x360/007ACC/FFFFFF?text=Cursor",
    description:
      "AI 驱动的代码编辑器，内置 GPT-4 辅助编程，大幅提升开发效率，适合接外包和开发副业。",
    pricingType: "免费/付费",
    categories: ["AI自动化", "AI赚钱"],
    images: [],
    features: ["AI代码补全", "智能重构", "自然语言编程", "多模型支持"],
    usecases: ["Web开发", "App开发", "代码审查", "技术外包"],
    users: ["程序员", "独立开发者", "技术创业者"],
    relatedSearches: ["AI编程", "代码助手"],
    pricings: ["免费版", "Pro $20/月"],
    links: {},
    voteCount: 890,
    metaKeywords: ["Cursor", "AI编程", "代码编辑器"],
    metaDescription: "Cursor - AI 代码编辑器",
    searchSuggestWords: ["cursor", "ai编程"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-jasper",
    userId: "00000000000000000",
    siteKey: "jasper",
    url: "https://www.jasper.ai",
    name: "Jasper",
    icon: "simple-icons:jasper",
    subCategory: "营销文案",
    featured: false,
    weight: 85,
    snapshot: "https://placehold.co/640x360/F97316/FFFFFF?text=Jasper",
    description:
      "专业 AI 营销写作工具，可生成广告文案、博客文章和社交媒体内容，助力内容营销变现。",
    pricingType: "付费",
    categories: ["AI写作", "AI赚钱"],
    images: [],
    features: ["营销文案", "SEO优化", "品牌语调", "模板库"],
    usecases: ["广告文案", "博客写作", "邮件营销", "产品描述"],
    users: ["营销人员", "自媒体人", "电商卖家"],
    relatedSearches: ["AI文案", "营销写作"],
    pricings: ["Creator $49/月"],
    links: {},
    voteCount: 450,
    metaKeywords: ["Jasper", "AI写作", "营销文案"],
    metaDescription: "Jasper - AI 营销写作工具",
    searchSuggestWords: ["jasper", "ai文案"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-copy-ai",
    userId: "00000000000000000",
    siteKey: "copy-ai",
    url: "https://www.copy.ai",
    name: "Copy.ai",
    icon: "simple-icons:copy",
    subCategory: "文案生成",
    featured: false,
    weight: 84,
    snapshot: "https://placehold.co/640x360/8B5CF6/FFFFFF?text=Copy.ai",
    description:
      "AI 文案生成器，快速产出社交媒体帖子、产品描述和邮件内容，适合副业内容创作。",
    pricingType: "免费/付费",
    categories: ["AI写作"],
    images: [],
    features: ["文案生成", "多语言", "工作流", "团队协作"],
    usecases: ["社交媒体", "产品文案", "邮件营销"],
    users: ["自媒体人", "电商运营", "自由职业者"],
    relatedSearches: ["AI文案"],
    pricings: ["免费版", "Pro $49/月"],
    links: {},
    voteCount: 380,
    metaKeywords: ["Copy.ai", "AI文案"],
    metaDescription: "Copy.ai - AI 文案生成器",
    searchSuggestWords: ["copy.ai", "文案"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-pika",
    userId: "00000000000000000",
    siteKey: "pika",
    url: "https://pika.art",
    name: "Pika",
    icon: "mdi:video",
    subCategory: "文生视频",
    featured: false,
    weight: 83,
    snapshot: "https://placehold.co/640x360/EC4899/FFFFFF?text=Pika",
    description:
      "AI 视频生成工具，支持文字和图片转视频，操作简单，适合短视频新手快速入门。",
    pricingType: "免费/付费",
    categories: ["AI视频"],
    images: [],
    features: ["文生视频", "图生视频", "视频编辑", "特效添加"],
    usecases: ["短视频", "动画制作", "社交媒体"],
    users: ["短视频博主", "内容创作者"],
    relatedSearches: ["AI视频"],
    pricings: ["免费版", "Standard $10/月"],
    links: {},
    voteCount: 520,
    metaKeywords: ["Pika", "AI视频"],
    metaDescription: "Pika - AI 视频生成工具",
    searchSuggestWords: ["pika", "ai视频"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-capcut",
    userId: "00000000000000000",
    siteKey: "capcut",
    url: "https://www.capcut.com",
    name: "CapCut",
    icon: "simple-icons:capcut",
    subCategory: "视频剪辑",
    featured: false,
    weight: 82,
    snapshot: "https://placehold.co/640x360/000000/FFFFFF?text=CapCut",
    description:
      "字节跳动出品的免费视频剪辑工具，内置 AI 功能如自动字幕、智能抠图，是抖音副业必备。",
    pricingType: "免费",
    categories: ["AI视频", "AI赚钱"],
    images: [],
    features: ["AI字幕", "智能抠图", "模板丰富", "一键导出"],
    usecases: ["抖音短视频", "Vlog剪辑", "带货视频"],
    users: ["短视频博主", "电商卖家"],
    relatedSearches: ["剪映", "视频剪辑"],
    pricings: ["免费"],
    links: {},
    voteCount: 1100,
    metaKeywords: ["CapCut", "剪映", "AI视频"],
    metaDescription: "CapCut - 免费 AI 视频剪辑",
    searchSuggestWords: ["capcut", "剪映"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-synthesia",
    userId: "00000000000000000",
    siteKey: "synthesia",
    url: "https://www.synthesia.io",
    name: "Synthesia",
    icon: "mdi:robot",
    subCategory: "数字人",
    featured: false,
    weight: 81,
    snapshot: "https://placehold.co/640x360/2563EB/FFFFFF?text=Synthesia",
    description:
      "AI 数字人视频平台，无需出镜即可制作专业讲解视频，适合知识付费和在线教育。",
    pricingType: "付费",
    categories: ["AI视频", "AI赚钱"],
    images: [],
    features: ["AI数字人", "多语言", "模板丰富", "企业级"],
    usecases: ["在线课程", "企业培训", "产品介绍"],
    users: ["知识博主", "企业培训", "教育工作者"],
    relatedSearches: ["数字人", "AI主播"],
    pricings: ["Starter $29/月"],
    links: {},
    voteCount: 340,
    metaKeywords: ["Synthesia", "AI数字人"],
    metaDescription: "Synthesia - AI 数字人视频",
    searchSuggestWords: ["synthesia", "数字人"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-leonardo",
    userId: "00000000000000000",
    siteKey: "leonardo-ai",
    url: "https://leonardo.ai",
    name: "Leonardo AI",
    icon: "mdi:palette",
    subCategory: "艺术创作",
    featured: false,
    weight: 80,
    snapshot: "https://placehold.co/640x360/059669/FFFFFF?text=Leonardo+AI",
    description:
      "免费 AI 绘图平台，提供多种模型和风格，适合游戏素材、概念设计和电商图片制作。",
    pricingType: "免费/付费",
    categories: ["AI绘图"],
    images: [],
    features: ["免费额度", "多模型", "ControlNet", "社区模型"],
    usecases: ["游戏素材", "概念设计", "电商图片"],
    users: ["游戏开发者", "设计师", "电商卖家"],
    relatedSearches: ["AI绘画", "免费AI绘图"],
    pricings: ["免费版", "Apprentice $12/月"],
    links: {},
    voteCount: 560,
    metaKeywords: ["Leonardo AI", "AI绘图"],
    metaDescription: "Leonardo AI - 免费 AI 绘图",
    searchSuggestWords: ["leonardo", "ai绘画"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-stable-diffusion",
    userId: "00000000000000000",
    siteKey: "stable-diffusion",
    url: "https://stability.ai",
    name: "Stable Diffusion",
    icon: "simple-icons:stability",
    subCategory: "开源绘图",
    featured: false,
    weight: 79,
    snapshot: "https://placehold.co/640x360/DC2626/FFFFFF?text=Stable+Diffusion",
    description:
      "开源 AI 图像生成模型，可本地部署免费使用，适合有技术基础的创作者深度定制。",
    pricingType: "免费/付费",
    categories: ["AI绘图"],
    images: [],
    features: ["开源免费", "本地部署", "高度定制", "社区生态"],
    usecases: ["艺术创作", "游戏素材", "研究开发"],
    users: ["开发者", "AI爱好者", "设计师"],
    relatedSearches: ["SD", "开源AI"],
    pricings: ["免费开源", "API付费"],
    links: {},
    voteCount: 720,
    metaKeywords: ["Stable Diffusion", "AI绘图", "开源"],
    metaDescription: "Stable Diffusion - 开源 AI 绘图",
    searchSuggestWords: ["stable diffusion", "sd"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-zapier",
    userId: "00000000000000000",
    siteKey: "zapier",
    url: "https://zapier.com",
    name: "Zapier",
    icon: "simple-icons:zapier",
    subCategory: "办公自动化",
    featured: false,
    weight: 78,
    snapshot: "https://placehold.co/640x360/FF4A00/FFFFFF?text=Zapier",
    description:
      "最流行的自动化工作流平台，连接 5000+ 应用，用 AI 实现业务流程自动化，节省大量时间。",
    pricingType: "免费/付费",
    categories: ["AI自动化", "AI办公"],
    images: [],
    features: ["工作流自动化", "5000+集成", "AI Actions", "无代码"],
    usecases: ["邮件自动化", "数据同步", "客户管理", "内容发布"],
    users: ["运营人员", "创业者", "自由职业者"],
    relatedSearches: ["自动化", "工作流"],
    pricings: ["免费版", "Starter $29.99/月"],
    links: {},
    voteCount: 490,
    metaKeywords: ["Zapier", "自动化", "工作流"],
    metaDescription: "Zapier - 自动化工作流平台",
    searchSuggestWords: ["zapier", "自动化"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-make",
    userId: "00000000000000000",
    siteKey: "make",
    url: "https://www.make.com",
    name: "Make",
    icon: "simple-icons:make",
    subCategory: "办公自动化",
    featured: false,
    weight: 77,
    snapshot: "https://placehold.co/640x360/6D28D9/FFFFFF?text=Make",
    description:
      "可视化自动化平台（原 Integromat），支持复杂工作流设计，适合进阶自动化需求。",
    pricingType: "免费/付费",
    categories: ["AI自动化"],
    images: [],
    features: ["可视化编辑", "复杂逻辑", "HTTP模块", "数据处理"],
    usecases: ["数据自动化", "API集成", "业务自动化"],
    users: ["运营人员", "开发者", "企业用户"],
    relatedSearches: ["Integromat", "自动化"],
    pricings: ["免费版", "Core $10.59/月"],
    links: {},
    voteCount: 310,
    metaKeywords: ["Make", "自动化", "Integromat"],
    metaDescription: "Make - 可视化自动化平台",
    searchSuggestWords: ["make", "integromat"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-n8n",
    userId: "00000000000000000",
    siteKey: "n8n",
    url: "https://n8n.io",
    name: "n8n",
    icon: "simple-icons:n8n",
    subCategory: "开源自动化",
    featured: false,
    weight: 76,
    snapshot: "https://placehold.co/640x360/EA4B71/FFFFFF?text=n8n",
    description:
      "开源工作流自动化工具，可自托管部署，集成 AI 节点，适合技术型创业者搭建自动化系统。",
    pricingType: "免费/付费",
    categories: ["AI自动化", "AI赚钱"],
    images: [],
    features: ["开源自托管", "AI节点", "400+集成", "JavaScript支持"],
    usecases: ["业务自动化", "AI Agent", "数据处理"],
    users: ["开发者", "技术创业者", "运维人员"],
    relatedSearches: ["开源自动化", "AI Agent"],
    pricings: ["免费自托管", "Cloud $24/月"],
    links: {},
    voteCount: 420,
    metaKeywords: ["n8n", "开源自动化", "AI Agent"],
    metaDescription: "n8n - 开源自动化平台",
    searchSuggestWords: ["n8n", "自动化"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-copilot",
    userId: "00000000000000000",
    siteKey: "copilot",
    url: "https://copilot.microsoft.com",
    name: "Microsoft Copilot",
    icon: "logos:microsoft-icon",
    subCategory: "办公助手",
    featured: false,
    weight: 75,
    snapshot: "https://placehold.co/640x360/0078D4/FFFFFF?text=Copilot",
    description:
      "微软 AI 助手，集成在 Office 365 中，可辅助写文档、做 PPT、分析 Excel，提升办公效率。",
    pricingType: "免费/付费",
    categories: ["AI办公"],
    images: [],
    features: ["Office集成", "文档写作", "数据分析", "PPT生成"],
    usecases: ["办公文档", "数据分析", "演示文稿", "邮件撰写"],
    users: ["白领", "学生", "管理者"],
    relatedSearches: ["Office AI", "微软AI"],
    pricings: ["免费版", "Copilot Pro $20/月"],
    links: {},
    voteCount: 650,
    metaKeywords: ["Copilot", "Microsoft", "AI办公"],
    metaDescription: "Microsoft Copilot - AI 办公助手",
    searchSuggestWords: ["copilot", "微软"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-gamma",
    userId: "00000000000000000",
    siteKey: "gamma",
    url: "https://gamma.app",
    name: "Gamma",
    icon: "mdi:presentation",
    subCategory: "PPT生成",
    featured: false,
    weight: 74,
    snapshot: "https://placehold.co/640x360/5B21B6/FFFFFF?text=Gamma",
    description:
      "AI 驱动的演示文稿和文档生成工具，输入主题即可生成精美 PPT，适合快速制作商业提案。",
    pricingType: "免费/付费",
    categories: ["AI办公", "AI赚钱"],
    images: [],
    features: ["AI生成PPT", "一键美化", "在线分享", "协作编辑"],
    usecases: ["商业提案", "课程讲义", "产品发布"],
    users: ["创业者", "咨询师", "教师"],
    relatedSearches: ["AI PPT", "演示文稿"],
    pricings: ["免费版", "Plus $10/月"],
    links: {},
    voteCount: 380,
    metaKeywords: ["Gamma", "AI PPT", "演示文稿"],
    metaDescription: "Gamma - AI 演示文稿生成",
    searchSuggestWords: ["gamma", "ppt"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-tome",
    userId: "00000000000000000",
    siteKey: "tome",
    url: "https://tome.app",
    name: "Tome",
    icon: "mdi:book-open-page-variant",
    subCategory: "演示文稿",
    featured: false,
    weight: 73,
    snapshot: "https://placehold.co/640x360/0EA5E9/FFFFFF?text=Tome",
    description:
      "AI 故事叙述和演示工具，可生成图文并茂的演示内容，适合品牌故事和产品介绍。",
    pricingType: "免费/付费",
    categories: ["AI办公"],
    images: [],
    features: ["AI叙事", "图文生成", "模板丰富", "在线分享"],
    usecases: ["品牌故事", "产品介绍", "创意展示"],
    users: ["品牌经理", "产品经理", "创作者"],
    relatedSearches: ["AI演示", "故事叙述"],
    pricings: ["免费版", "Pro $16/月"],
    links: {},
    voteCount: 290,
    metaKeywords: ["Tome", "AI演示", "故事叙述"],
    metaDescription: "Tome - AI 故事演示工具",
    searchSuggestWords: ["tome", "演示"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-futurepedia",
    userId: "00000000000000000",
    siteKey: "futurepedia",
    url: "https://www.futurepedia.io",
    name: "Futurepedia",
    icon: "mdi:compass",
    subCategory: "工具目录",
    featured: true,
    weight: 72,
    snapshot: "https://www.google.com/s2/favicons?domain=futurepedia.io&sz=64",
    description:
      "全球最大的 AI 工具目录，每日更新，收录数万款 AI 工具，是发现新工具的首选平台。",
    pricingType: "免费",
    categories: ["AI目录导航", "AI赚钱"],
    images: [],
    features: ["每日更新", "数万工具", "智能搜索", "分类详细"],
    usecases: ["工具发现", "竞品调研", "行业分析"],
    users: ["开发者", "创业者", "AI爱好者"],
    relatedSearches: ["AI工具目录", "Futurepedia"],
    pricings: ["免费"],
    links: {},
    voteCount: 2800,
    metaKeywords: ["Futurepedia", "AI目录", "AI工具"],
    metaDescription: "Futurepedia - 全球最大的 AI 工具目录",
    searchSuggestWords: ["futurepedia", "ai目录"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-futuretools",
    userId: "00000000000000000",
    siteKey: "futuretools",
    url: "https://www.futuretools.io",
    name: "FutureTools",
    icon: "mdi:tools",
    subCategory: "工具集合",
    featured: true,
    weight: 71,
    snapshot: "https://www.google.com/s2/favicons?domain=futuretools.io&sz=64",
    description:
      "AI 工具集合与整理平台，帮助用户发现最适合自己的 AI 工具，提升工作效率。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["工具整理", "分类浏览", "用户评价", "收藏功能"],
    usecases: ["工具发现", "效率提升", "技能升级"],
    users: ["专业人士", "学生", "创业者"],
    relatedSearches: ["AI工具", "FutureTools"],
    pricings: ["免费"],
    links: {},
    voteCount: 2100,
    metaKeywords: ["FutureTools", "AI工具", "效率工具"],
    metaDescription: "FutureTools - AI 工具集合平台",
    searchSuggestWords: ["futuretools", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-toolify",
    userId: "00000000000000000",
    siteKey: "toolify",
    url: "https://www.toolify.ai",
    name: "Toolify.ai",
    icon: "mdi:robot-search",
    subCategory: "工具目录",
    featured: false,
    weight: 70,
    snapshot: "https://www.google.com/s2/favicons?domain=toolify.ai&sz=64",
    description:
      "AI 公司和工具目录，由 ChatGPT 每日自动更新，提供最新最全面的 AI 工具信息。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["自动更新", "AI公司", "工具对比", "详细信息"],
    usecases: ["工具发现", "市场研究", "竞品分析"],
    users: ["开发者", "投资人", "创业者"],
    relatedSearches: ["Toolify", "AI公司"],
    pricings: ["免费"],
    links: {},
    voteCount: 1500,
    metaKeywords: ["Toolify", "AI公司", "AI工具目录"],
    metaDescription: "Toolify.ai - AI 公司和工具目录",
    searchSuggestWords: ["toolify", "ai公司"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-altern",
    userId: "00000000000000000",
    siteKey: "altern",
    url: "https://altern.ai",
    name: "Altern",
    icon: "mdi:magnify",
    subCategory: "工具搜索",
    featured: false,
    weight: 69,
    snapshot: "https://www.google.com/s2/favicons?domain=altern.ai&sz=64",
    description:
      "AI 工具搜索引擎，帮助用户发现与 AI 相关的各类工具和资源。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["AI搜索", "工具发现", "分类浏览", "推荐系统"],
    usecases: ["工具搜索", "资源发现", "学习推荐"],
    users: ["AI爱好者", "开发者", "学生"],
    relatedSearches: ["Altern", "AI搜索"],
    pricings: ["免费"],
    links: {},
    voteCount: 1200,
    metaKeywords: ["Altern", "AI搜索", "工具发现"],
    metaDescription: "Altern - AI 工具搜索引擎",
    searchSuggestWords: ["altern", "ai搜索"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-productivity-directory",
    userId: "00000000000000000",
    siteKey: "productivity-directory",
    url: "https://productivity.directory",
    name: "Productivity Directory",
    icon: "mdi:folder-star",
    subCategory: "生产力工具",
    featured: false,
    weight: 68,
    snapshot: "https://www.google.com/s2/favicons?domain=productivity.directory&sz=64",
    description:
      "生产力工具目录，专注于 AI 生产力工具的发现、搜索和评测。",
    pricingType: "免费",
    categories: ["AI目录导航", "AI办公"],
    images: [],
    features: ["生产力工具", "用户评测", "分类筛选", "工具对比"],
    usecases: ["效率提升", "工具评测", "工作流优化"],
    users: ["职场人士", "自由职业者", "创业者"],
    relatedSearches: ["生产力工具", "效率工具"],
    pricings: ["免费"],
    links: {},
    voteCount: 980,
    metaKeywords: ["Productivity Directory", "生产力工具", "AI办公"],
    metaDescription: "Productivity Directory - 生产力工具目录",
    searchSuggestWords: ["productivity", "生产力"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-there-s-an-ai",
    userId: "00000000000000000",
    siteKey: "there-s-an-ai",
    url: "https://theresanai.com",
    name: "There's An AI",
    icon: "mdi:robot-outline",
    subCategory: "工具聚合",
    featured: false,
    weight: 67,
    snapshot: "https://www.google.com/s2/favicons?domain=theresanai.com&sz=64",
    description:
      "AI 工具聚合平台，收录各类 AI 工具，帮助用户找到解决问题的最佳方案。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["工具聚合", "智能推荐", "分类浏览", "用户评论"],
    usecases: ["问题解决", "工具发现", "方案对比"],
    users: ["普通用户", "专业人士", "企业用户"],
    relatedSearches: ["AI工具聚合", "There's An AI"],
    pricings: ["免费"],
    links: {},
    voteCount: 850,
    metaKeywords: ["There's An AI", "AI工具聚合"],
    metaDescription: "There's An AI - AI 工具聚合平台",
    searchSuggestWords: ["theresanai", "ai聚合"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-aidirectory",
    userId: "00000000000000000",
    siteKey: "aidirectory",
    url: "https://aidirectory.wiki",
    name: "AI Directory",
    icon: "mdi:folder-search",
    subCategory: "精选目录",
    featured: false,
    weight: 66,
    snapshot: "https://www.google.com/s2/favicons?domain=aidirectory.wiki&sz=64",
    description:
      "AI 工具精选目录，收集各类 AI 驱动的生产力、创意和商业工具。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["精选工具", "分类清晰", "详细介绍", "持续更新"],
    usecases: ["工具发现", "学习参考", "商业应用"],
    users: ["创业者", "设计师", "开发者"],
    relatedSearches: ["AI目录", "AI工具精选"],
    pricings: ["免费"],
    links: {},
    voteCount: 720,
    metaKeywords: ["AI Directory", "AI工具目录", "精选工具"],
    metaDescription: "AI Directory - AI 工具精选目录",
    searchSuggestWords: ["aidirectory", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-aidirs",
    userId: "00000000000000000",
    siteKey: "aidirs",
    url: "https://aidirs.best",
    name: "AiDirs",
    icon: "mdi:share-variant",
    subCategory: "工具分享",
    featured: false,
    weight: 65,
    snapshot: "https://www.google.com/s2/favicons?domain=aidirs.best&sz=64",
    description:
      "发现和分享最佳 AI 工具的平台，帮助用户找到最适合自己需求的工具。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["工具分享", "用户推荐", "分类浏览", "收藏功能"],
    usecases: ["工具发现", "社区分享", "学习交流"],
    users: ["AI爱好者", "专业人士", "学生"],
    relatedSearches: ["AiDirs", "AI工具分享"],
    pricings: ["免费"],
    links: {},
    voteCount: 650,
    metaKeywords: ["AiDirs", "AI工具分享", "工具推荐"],
    metaDescription: "AiDirs - AI 工具发现与分享平台",
    searchSuggestWords: ["aidirs", "ai分享"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-deepseek",
    userId: "00000000000000000",
    siteKey: "deepseek",
    url: "https://chat.deepseek.com",
    name: "DeepSeek",
    icon: "simple-icons:deepseek",
    subCategory: "通用对话",
    featured: true,
    weight: 94,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fchat.deepseek.com?w=640",
    description: "深度求索推出的强大 AI 对话模型，以超长上下文和推理能力著称，完全免费使用。",
    pricingType: "免费",
    categories: ["AI对话", "AI编程"],
    images: [],
    features: ["超长上下文(1M tokens)", "深度推理", "文件上传", "联网搜索", "完全免费"],
    usecases: ["编程开发", "文档分析", "深度问答", "内容创作"],
    users: ["程序员", "研究人员", "学生", "内容创作者"],
    relatedSearches: ["DeepSeek"],
    pricings: ["完全免费"],
    links: {},
    voteCount: 900,
    metaKeywords: ["DeepSeek", "AI工具"],
    metaDescription: "DeepSeek - AI工具",
    searchSuggestWords: ["deepseek"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-claude",
    userId: "00000000000000000",
    siteKey: "claude",
    url: "https://claude.ai",
    name: "Claude",
    icon: "simple-icons:claude",
    subCategory: "通用对话",
    featured: true,
    weight: 93,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fclaude.ai?w=640",
    description: "Anthropic 推出的 AI 助手，擅长深度分析、长文写作和代码生成，以安全可靠著称。",
    pricingType: "免费/付费",
    categories: ["AI对话", "AI写作", "AI编程"],
    images: [],
    features: ["超长上下文(200K)", "深度分析", "代码生成", "文档理解", "Projects"],
    usecases: ["长文分析", "编程开发", "学术研究", "内容撰写"],
    users: ["程序员", "研究人员", "作家", "分析师"],
    relatedSearches: ["Claude", "Anthropic"],
    pricings: ["免费版", "Pro $20/月"],
    links: {},
    voteCount: 880,
    metaKeywords: ["Claude", "AI工具"],
    metaDescription: "Claude - AI工具",
    searchSuggestWords: ["claude"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-gemini",
    userId: "00000000000000000",
    siteKey: "gemini",
    url: "https://gemini.google.com",
    name: "Gemini",
    icon: "logos:google-gemini",
    subCategory: "通用对话",
    featured: true,
    weight: 92,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fgemini.google.com?w=640",
    description: "Google 推出的多模态 AI 模型，支持文本、图像、音频和视频理解，与 Google 生态深度集成。",
    pricingType: "免费/付费",
    categories: ["AI对话", "AI搜索"],
    images: [],
    features: ["多模态理解", "联网搜索", "Google集成", "长上下文", "文件分析"],
    usecases: ["信息检索", "数据分析", "内容创作", "学习辅导"],
    users: ["普通用户", "学生", "研究人员", "办公人员"],
    relatedSearches: ["Gemini", "Google AI"],
    pricings: ["免费版", "Advanced $19.99/月"],
    links: {},
    voteCount: 860,
    metaKeywords: ["Gemini", "AI工具"],
    metaDescription: "Gemini - AI工具",
    searchSuggestWords: ["gemini"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-kimi",
    userId: "00000000000000000",
    siteKey: "kimi",
    url: "https://kimi.moonshot.cn",
    name: "Kimi",
    icon: "mdi:robot-excited-outline",
    subCategory: "国产对话",
    featured: true,
    weight: 91,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fkimi.moonshot.cn?w=640",
    description: "月之暗面推出的中文 AI 助手，以超长上下文处理能力闻名，擅长文档阅读和分析。",
    pricingType: "免费/付费",
    categories: ["AI对话"],
    images: [],
    features: ["超长上下文(200万字)", "文档分析", "联网搜索", "多文件处理"],
    usecases: ["论文阅读", "合同分析", "研究报告", "知识问答"],
    users: ["学生", "研究人员", "律师", "办公人员"],
    relatedSearches: ["Kimi", "月之暗面"],
    pricings: ["免费版", "会员 $12.99/月"],
    links: {},
    voteCount: 840,
    metaKeywords: ["Kimi", "AI工具"],
    metaDescription: "Kimi - AI工具",
    searchSuggestWords: ["kimi"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-doubao",
    userId: "00000000000000000",
    siteKey: "doubao",
    url: "https://www.doubao.com",
    name: "豆包",
    icon: "mdi:robot-happy-outline",
    subCategory: "国产对话",
    featured: true,
    weight: 90,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.doubao.com?w=640",
    description: "字节跳动推出的 AI 对话助手，功能全面，支持文本生成、图像理解、语音对话。",
    pricingType: "免费",
    categories: ["AI对话", "AI写作"],
    images: [],
    features: ["图文理解", "语音对话", "AI搜索", "插件生态", "完全免费"],
    usecases: ["日常问答", "写作辅助", "学习辅导", "编程帮助"],
    users: ["普通用户", "学生", "内容创作者"],
    relatedSearches: ["豆包", "字节跳动"],
    pricings: ["完全免费"],
    links: {},
    voteCount: 820,
    metaKeywords: ["豆包", "AI工具"],
    metaDescription: "豆包 - AI工具",
    searchSuggestWords: ["doubao"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-tongyi",
    userId: "00000000000000000",
    siteKey: "tongyi",
    url: "https://tongyi.aliyun.com",
    name: "通义千问",
    icon: "mdi:robot-industrial-outline",
    subCategory: "国产对话",
    featured: false,
    weight: 85,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Ftongyi.aliyun.com?w=640",
    description: "阿里巴巴推出的 AI 大模型，支持对话、文档处理、图像生成、代码辅助等功能。",
    pricingType: "免费/付费",
    categories: ["AI对话", "AI办公"],
    images: [],
    features: ["多模态理解", "文档处理", "代码辅助", "图像生成", "阿里云集成"],
    usecases: ["办公辅助", "开发编程", "数据分析", "内容生成"],
    users: ["企业用户", "开发者", "办公人员"],
    relatedSearches: ["通义千问", "阿里AI"],
    pricings: ["免费版", "企业版按量计费"],
    links: {},
    voteCount: 780,
    metaKeywords: ["通义千问", "AI工具"],
    metaDescription: "通义千问 - AI工具",
    searchSuggestWords: ["tongyi"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-github-copilot",
    userId: "00000000000000000",
    siteKey: "github-copilot",
    url: "https://github.com/features/copilot",
    name: "GitHub Copilot",
    icon: "logos:github-copilot",
    subCategory: "代码助手",
    featured: true,
    weight: 89,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fgithub.com%2Ffeatures%2Fcopilot?w=640",
    description: "GitHub 推出的 AI 编程助手，集成在 VS Code、JetBrains 等 IDE 中，提供实时代码补全。",
    pricingType: "免费/付费",
    categories: ["AI编程"],
    images: [],
    features: ["实时代码补全", "对话式编程", "多IDE支持", "代码审查", "多语言"],
    usecases: ["日常开发", "代码审查", "快速原型", "学习新语言"],
    users: ["程序员", "开发者", "学生"],
    relatedSearches: ["GitHub Copilot"],
    pricings: ["免费版", "个人 $10/月"],
    links: {},
    voteCount: 800,
    metaKeywords: ["GitHub Copilot", "AI工具"],
    metaDescription: "GitHub Copilot - AI工具",
    searchSuggestWords: ["github-copilot"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-v0",
    userId: "00000000000000000",
    siteKey: "v0",
    url: "https://v0.dev",
    name: "v0.dev",
    icon: "logos:vercel-icon",
    subCategory: "应用生成",
    featured: true,
    weight: 88,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fv0.dev?w=640",
    description: "Vercel 推出的 AI UI 生成工具，通过自然语言描述即可生成 React 组件和前端页面。",
    pricingType: "免费/付费",
    categories: ["AI编程"],
    images: [],
    features: ["自然语言生成UI", "React组件", "Tailwind CSS", "shadcn/ui", "实时预览"],
    usecases: ["前端开发", "原型设计", "组件生成", "Landing Page"],
    users: ["前端开发者", "设计师", "全栈工程师"],
    relatedSearches: ["v0.dev", "Vercel"],
    pricings: ["免费版", "Pro $20/月"],
    links: {},
    voteCount: 760,
    metaKeywords: ["v0.dev", "AI工具"],
    metaDescription: "v0.dev - AI工具",
    searchSuggestWords: ["v0"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-bolt",
    userId: "00000000000000000",
    siteKey: "bolt",
    url: "https://bolt.new",
    name: "Bolt.new",
    icon: "mdi:lightning-bolt",
    subCategory: "应用生成",
    featured: true,
    weight: 87,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fbolt.new?w=640",
    description: "AI 全栈 Web 应用生成器，通过描述即可直接创建和部署完整的 Web 应用。",
    pricingType: "免费/付费",
    categories: ["AI编程"],
    images: [],
    features: ["全栈应用生成", "实时编辑", "一键部署", "多框架支持"],
    usecases: ["快速原型开发", "MVP构建", "个人项目", "学习实验"],
    users: ["全栈开发者", "创业团队", "产品经理"],
    relatedSearches: ["Bolt.new"],
    pricings: ["免费版", "Pro $20/月"],
    links: {},
    voteCount: 740,
    metaKeywords: ["Bolt.new", "AI工具"],
    metaDescription: "Bolt.new - AI工具",
    searchSuggestWords: ["bolt"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-lovable",
    userId: "00000000000000000",
    siteKey: "lovable",
    url: "https://lovable.dev",
    name: "Lovable",
    icon: "mdi:heart-outline",
    subCategory: "应用生成",
    featured: false,
    weight: 83,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Flovable.dev?w=640",
    description: "AI 全栈应用构建平台，通过自然语言描述快速生成带有后端和前端的完整应用。",
    pricingType: "免费/付费",
    categories: ["AI编程"],
    images: [],
    features: ["全栈生成", "Supabase集成", "实时预览", "一键部署"],
    usecases: ["快速建站", "MVP开发", "内部工具", "原型验证"],
    users: ["创业者", "开发者", "产品经理"],
    relatedSearches: ["Lovable"],
    pricings: ["免费版", "Starter $25/月"],
    links: {},
    voteCount: 680,
    metaKeywords: ["Lovable", "AI工具"],
    metaDescription: "Lovable - AI工具",
    searchSuggestWords: ["lovable"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-windsurf",
    userId: "00000000000000000",
    siteKey: "windsurf",
    url: "https://codeium.com/windsurf",
    name: "Windsurf",
    icon: "mdi:weather-windy",
    subCategory: "AI IDE",
    featured: false,
    weight: 82,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fcodeium.com%2Fwindsurf?w=640",
    description: "Codeium 推出的 AI 原生 IDE，基于 VS Code 构建，提供深度集成的 AI 编程体验。",
    pricingType: "免费/付费",
    categories: ["AI编程"],
    images: [],
    features: ["AI原生IDE", "多文件编辑", "智能代理", "代码补全", "上下文理解"],
    usecases: ["日常开发", "代码重构", "项目开发"],
    users: ["程序员", "全栈开发者", "技术团队"],
    relatedSearches: ["Windsurf", "Codeium"],
    pricings: ["免费版", "Pro $15/月"],
    links: {},
    voteCount: 720,
    metaKeywords: ["Windsurf", "AI工具"],
    metaDescription: "Windsurf - AI工具",
    searchSuggestWords: ["windsurf"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-firefly",
    userId: "00000000000000000",
    siteKey: "firefly",
    url: "https://firefly.adobe.com",
    name: "Adobe Firefly",
    icon: "logos:adobe-firefly",
    subCategory: "设计工具",
    featured: true,
    weight: 86,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Ffirefly.adobe.com?w=640",
    description: "Adobe 推出的生成式 AI 图像工具，集成在 Photoshop、Illustrator 等创意云产品中。",
    pricingType: "免费/付费",
    categories: ["AI制图"],
    images: [],
    features: ["文本生成图像", "生成式填充", "文字效果", "Adobe集成", "商用安全"],
    usecases: ["商业设计", "广告创意", "社交媒体", "产品展示"],
    users: ["设计师", "创意人员", "营销人员"],
    relatedSearches: ["Adobe Firefly"],
    pricings: ["免费版", "Premium $4.99/月"],
    links: {},
    voteCount: 700,
    metaKeywords: ["Adobe Firefly", "AI工具"],
    metaDescription: "Adobe Firefly - AI工具",
    searchSuggestWords: ["firefly"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-ideogram",
    userId: "00000000000000000",
    siteKey: "ideogram",
    url: "https://ideogram.ai",
    name: "Ideogram",
    icon: "mdi:palette-outline",
    subCategory: "图像生成",
    featured: false,
    weight: 78,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fideogram.ai?w=640",
    description: "以精准的文字渲染能力著称的 AI 图像生成平台，适合生成带文字的海报和 Logo。",
    pricingType: "免费/付费",
    categories: ["AI制图"],
    images: [],
    features: ["精准文字渲染", "高画质生成", "风格多样", "图片编辑"],
    usecases: ["海报设计", "Logo制作", "社交媒体", "广告图"],
    users: ["设计师", "营销人员", "内容创作者"],
    relatedSearches: ["Ideogram"],
    pricings: ["免费版", "Plus $20/月"],
    links: {},
    voteCount: 650,
    metaKeywords: ["Ideogram", "AI工具"],
    metaDescription: "Ideogram - AI工具",
    searchSuggestWords: ["ideogram"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-recraft",
    userId: "00000000000000000",
    siteKey: "recraft",
    url: "https://www.recraft.ai",
    name: "Recraft",
    icon: "mdi:vector-polyline",
    subCategory: "设计工具",
    featured: false,
    weight: 75,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.recraft.ai?w=640",
    description: "AI 矢量图和图标生成工具，支持生成 SVG 矢量图形、品牌素材和 UI 图标。",
    pricingType: "免费/付费",
    categories: ["AI制图"],
    images: [],
    features: ["矢量图生成", "SVG输出", "品牌风格保持", "图标生成", "多种风格"],
    usecases: ["Logo设计", "UI图标", "品牌素材", "插画"],
    users: ["UI设计师", "品牌设计师", "产品经理"],
    relatedSearches: ["Recraft"],
    pricings: ["免费版", "Pro $20/月"],
    links: {},
    voteCount: 580,
    metaKeywords: ["Recraft", "AI工具"],
    metaDescription: "Recraft - AI工具",
    searchSuggestWords: ["recraft"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-seaart",
    userId: "00000000000000000",
    siteKey: "seaart",
    url: "https://www.seaart.ai",
    name: "SeaArt",
    icon: "mdi:wave",
    subCategory: "图像生成",
    featured: false,
    weight: 72,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.seaart.ai?w=640",
    description: "受欢迎的国产 AI 绘画平台，基于 Stable Diffusion，提供丰富的模型和 ControlNet 功能。",
    pricingType: "免费/付费",
    categories: ["AI制图"],
    images: [],
    features: ["丰富的模型库", "ControlNet支持", "在线训练", "图片后期", "社区分享"],
    usecases: ["AI绘画", "插画创作", "概念设计", "动漫生成"],
    users: ["画师", "设计师", "AI艺术爱好者"],
    relatedSearches: ["SeaArt"],
    pricings: ["免费版", "Pro ¥69/月"],
    links: {},
    voteCount: 630,
    metaKeywords: ["SeaArt", "AI工具"],
    metaDescription: "SeaArt - AI工具",
    searchSuggestWords: ["seaart"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-kling",
    userId: "00000000000000000",
    siteKey: "kling",
    url: "https://kling.kuaishou.com",
    name: "可灵AI",
    icon: "mdi:video-vintage",
    subCategory: "视频生成",
    featured: true,
    weight: 84,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fkling.kuaishou.com?w=640",
    description: "快手推出的 AI 视频生成工具，支持文生视频和图生视频，以高画质和物理仿真能力受到关注。",
    pricingType: "免费/付费",
    categories: ["AI视频", "AI制图"],
    images: [],
    features: ["文生视频", "图生视频", "高画质", "物理仿真", "运动笔刷"],
    usecases: ["短视频创作", "广告制作", "创意视频", "内容营销"],
    users: ["视频创作者", "营销人员", "短视频博主"],
    relatedSearches: ["可灵AI", "Kling"],
    pricings: ["免费试用", "会员 ¥66/月"],
    links: {},
    voteCount: 750,
    metaKeywords: ["可灵AI", "AI工具"],
    metaDescription: "可灵AI - AI工具",
    searchSuggestWords: ["kling"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-luma",
    userId: "00000000000000000",
    siteKey: "luma",
    url: "https://lumalabs.ai",
    name: "Luma Dream Machine",
    icon: "mdi:dream",
    subCategory: "视频生成",
    featured: true,
    weight: 82,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Flumalabs.ai?w=640",
    description: "Luma AI 推出的视频生成模型，以高质量的视频生成和流畅的动作效果著称。",
    pricingType: "免费/付费",
    categories: ["AI视频"],
    images: [],
    features: ["高质量视频生成", "物理真实", "图生视频", "快速生成"],
    usecases: ["创意视频", "广告制作", "概念展示", "影视预览"],
    users: ["视频创作者", "电影人", "广告人"],
    relatedSearches: ["Luma", "Dream Machine"],
    pricings: ["免费版", "Plus $29.99/月"],
    links: {},
    voteCount: 710,
    metaKeywords: ["Luma Dream Machine", "AI工具"],
    metaDescription: "Luma Dream Machine - AI工具",
    searchSuggestWords: ["luma"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-vidu",
    userId: "00000000000000000",
    siteKey: "vidu",
    url: "https://www.vidu.com",
    name: "Vidu",
    icon: "mdi:movie-open-outline",
    subCategory: "视频生成",
    featured: false,
    weight: 73,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.vidu.com?w=640",
    description: "生数科技推出的国产 AI 视频生成平台，支持文生视频和图生视频，具有高一致性和可控性。",
    pricingType: "免费/付费",
    categories: ["AI视频"],
    images: [],
    features: ["文生视频", "图生视频", "角色一致", "风格控制", "高清输出"],
    usecases: ["短视频创作", "广告营销", "影视制作"],
    users: ["视频创作者", "营销人员"],
    relatedSearches: ["Vidu", "生数科技"],
    pricings: ["免费试用", "会员 ¥79/月"],
    links: {},
    voteCount: 590,
    metaKeywords: ["Vidu", "AI工具"],
    metaDescription: "Vidu - AI工具",
    searchSuggestWords: ["vidu"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-haiper",
    userId: "00000000000000000",
    siteKey: "haiper",
    url: "https://haiper.ai",
    name: "Haiper",
    icon: "mdi:video-outline",
    subCategory: "视频生成",
    featured: false,
    weight: 68,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fhaiper.ai?w=640",
    description: "AI 视频生成平台，提供高质量的视频生成、视频修复和动画制作功能。",
    pricingType: "免费/付费",
    categories: ["AI视频"],
    images: [],
    features: ["文生视频", "视频修复", "动画制作", "风格迁移"],
    usecases: ["社交媒体视频", "内容创作", "动画制作"],
    users: ["内容创作者", "社交媒体运营"],
    relatedSearches: ["Haiper"],
    pricings: ["免费版", "Pro $30/月"],
    links: {},
    voteCount: 540,
    metaKeywords: ["Haiper", "AI工具"],
    metaDescription: "Haiper - AI工具",
    searchSuggestWords: ["haiper"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-suno",
    userId: "00000000000000000",
    siteKey: "suno",
    url: "https://suno.ai",
    name: "Suno",
    icon: "mdi:music-note",
    subCategory: "音乐生成",
    featured: true,
    weight: 80,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fsuno.ai?w=640",
    description: "领先的 AI 音乐生成平台，通过文字描述即可生成完整歌曲，包括歌词和旋律。",
    pricingType: "免费/付费",
    categories: ["AI音乐"],
    images: [],
    features: ["文生音乐", "歌词生成", "多种风格", "人声演唱", "扩展创作"],
    usecases: ["音乐创作", "背景音乐", "短视频配乐", "个人创作"],
    users: ["音乐人", "内容创作者", "短视频博主"],
    relatedSearches: ["Suno"],
    pricings: ["免费版", "Pro $10/月"],
    links: {},
    voteCount: 760,
    metaKeywords: ["Suno", "AI工具"],
    metaDescription: "Suno - AI工具",
    searchSuggestWords: ["suno"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-udio",
    userId: "00000000000000000",
    siteKey: "udio",
    url: "https://www.udio.com",
    name: "Udio",
    icon: "mdi:music-circle-outline",
    subCategory: "音乐生成",
    featured: true,
    weight: 76,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.udio.com?w=640",
    description: "高质量 AI 音乐生成平台，专注于生成专业级音乐作品，支持自定义歌词。",
    pricingType: "免费/付费",
    categories: ["AI音乐"],
    images: [],
    features: ["高质量音乐生成", "自定义歌词", "精细控制", "多种流派", "专业音质"],
    usecases: ["专业音乐制作", "影视配乐", "游戏音乐", "个人项目"],
    users: ["音乐制作人", "作曲家", "内容创作者"],
    relatedSearches: ["Udio"],
    pricings: ["免费版", "Pro $10/月"],
    links: {},
    voteCount: 660,
    metaKeywords: ["Udio", "AI工具"],
    metaDescription: "Udio - AI工具",
    searchSuggestWords: ["udio"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-soundraw",
    userId: "00000000000000000",
    siteKey: "soundraw",
    url: "https://soundraw.io",
    name: "Soundraw",
    icon: "mdi:music-box-outline",
    subCategory: "音乐生成",
    featured: false,
    weight: 64,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fsoundraw.io?w=640",
    description: "AI 音乐创作平台，专注于免版税背景音乐生成，支持自定义曲风、节奏和情绪。",
    pricingType: "免费/付费",
    categories: ["AI音乐"],
    images: [],
    features: ["免版税音乐", "自定义控制", "多种风格", "无限生成"],
    usecases: ["视频配乐", "播客BGM", "游戏音乐", "商业使用"],
    users: ["视频创作者", "播客主", "游戏开发者"],
    relatedSearches: ["Soundraw"],
    pricings: ["免费版", "Creator $16.99/月"],
    links: {},
    voteCount: 460,
    metaKeywords: ["Soundraw", "AI工具"],
    metaDescription: "Soundraw - AI工具",
    searchSuggestWords: ["soundraw"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-perplexity",
    userId: "00000000000000000",
    siteKey: "perplexity",
    url: "https://www.perplexity.ai",
    name: "Perplexity",
    icon: "simple-icons:perplexity",
    subCategory: "AI搜索",
    featured: true,
    weight: 85,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.perplexity.ai?w=640",
    description: "AI 搜索引擎，结合大语言模型和实时网络搜索，提供带引用来源的准确答案。",
    pricingType: "免费/付费",
    categories: ["AI搜索", "AI对话"],
    images: [],
    features: ["实时搜索", "引用来源", "深度研究", "文件上传", "多模型支持"],
    usecases: ["学术研究", "日常搜索", "深度调研", "技术查询"],
    users: ["研究人员", "学生", "职场人士", "普通用户"],
    relatedSearches: ["Perplexity"],
    pricings: ["免费版", "Pro $20/月"],
    links: {},
    voteCount: 830,
    metaKeywords: ["Perplexity", "AI工具"],
    metaDescription: "Perplexity - AI工具",
    searchSuggestWords: ["perplexity"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-metaso",
    userId: "00000000000000000",
    siteKey: "metaso",
    url: "https://metaso.cn",
    name: "秘塔AI",
    icon: "mdi:search-web",
    subCategory: "AI搜索",
    featured: true,
    weight: 81,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fmetaso.cn?w=640",
    description: "国产 AI 搜索引擎，提供精准的搜索结果和结构化信息展示，支持深度搜索和大纲模式。",
    pricingType: "免费",
    categories: ["AI搜索"],
    images: [],
    features: ["AI搜索", "大纲模式", "深度搜索", "无广告", "完全免费"],
    usecases: ["学术搜索", "信息调研", "知识获取", "工作查询"],
    users: ["学生", "研究人员", "职场人士"],
    relatedSearches: ["秘塔AI", "Metaso"],
    pricings: ["完全免费"],
    links: {},
    voteCount: 720,
    metaKeywords: ["秘塔AI", "AI工具"],
    metaDescription: "秘塔AI - AI工具",
    searchSuggestWords: ["metaso"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-phind",
    userId: "00000000000000000",
    siteKey: "phind",
    url: "https://www.phind.com",
    name: "Phind",
    icon: "mdi:lightbulb-question-outline",
    subCategory: "AI搜索",
    featured: false,
    weight: 74,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.phind.com?w=640",
    description: "面向开发者的 AI 搜索引擎，专注于技术问题解答，提供代码示例和详细说明。",
    pricingType: "免费/付费",
    categories: ["AI搜索", "AI编程"],
    images: [],
    features: ["技术搜索", "代码示例", "详细解答", "多模型", "上下文理解"],
    usecases: ["技术查询", "Debug", "学习新技术", "代码审查"],
    users: ["程序员", "技术爱好者", "IT从业者"],
    relatedSearches: ["Phind"],
    pricings: ["免费版", "Pro $19/月"],
    links: {},
    voteCount: 600,
    metaKeywords: ["Phind", "AI工具"],
    metaDescription: "Phind - AI工具",
    searchSuggestWords: ["phind"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-you",
    userId: "00000000000000000",
    siteKey: "you",
    url: "https://you.com",
    name: "You.com",
    icon: "mdi:alpha-y-box-outline",
    subCategory: "AI搜索",
    featured: false,
    weight: 66,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fyou.com?w=640",
    description: "AI 驱动搜索引擎，提供多模式搜索、聊天和代码生成等功能，注重用户隐私保护。",
    pricingType: "免费/付费",
    categories: ["AI搜索"],
    images: [],
    features: ["AI搜索", "多模式", "代码生成", "隐私保护", "应用集成"],
    usecases: ["日常搜索", "内容创作", "代码生成"],
    users: ["普通用户", "开发者", "隐私关注者"],
    relatedSearches: ["You.com"],
    pricings: ["免费版", "Pro $14.99/月"],
    links: {},
    voteCount: 520,
    metaKeywords: ["You.com", "AI工具"],
    metaDescription: "You.com - AI工具",
    searchSuggestWords: ["you"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-khanmigo",
    userId: "00000000000000000",
    siteKey: "khanmigo",
    url: "https://www.khanacademy.org/khan-labs",
    name: "Khanmigo",
    icon: "mdi:school-outline",
    subCategory: "AI辅导",
    featured: true,
    weight: 75,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.khanacademy.org%2Fkhan-labs?w=640",
    description: "可汗学院推出的 AI 学习助手，作为学生的 AI 导师和教师的课堂助手，引导式教学。",
    pricingType: "付费",
    categories: ["AI教育"],
    images: [],
    features: ["AI导师", "引导式教学", "数学辅导", "编程教学", "教师助手"],
    usecases: ["课后辅导", "自主学习", "课堂教学", "作业帮助"],
    users: ["学生", "教师", "自学者"],
    relatedSearches: ["Khanmigo", "可汗学院"],
    pricings: ["$44/年"],
    links: {},
    voteCount: 620,
    metaKeywords: ["Khanmigo", "AI工具"],
    metaDescription: "Khanmigo - AI工具",
    searchSuggestWords: ["khanmigo"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-quizlet",
    userId: "00000000000000000",
    siteKey: "quizlet",
    url: "https://quizlet.com",
    name: "Quizlet",
    icon: "logos:quizlet",
    subCategory: "学习工具",
    featured: false,
    weight: 67,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fquizlet.com?w=640",
    description: "AI 增强的学习平台，通过闪卡、测试和游戏化学习帮助记忆，集成了 AI 生成学习材料。",
    pricingType: "免费/付费",
    categories: ["AI教育"],
    images: [],
    features: ["闪卡学习", "AI生成", "测试模式", "游戏化", "协作学习"],
    usecases: ["语言学习", "考试准备", "知识点记忆", "课堂学习"],
    users: ["学生", "语言学习者", "教师"],
    relatedSearches: ["Quizlet"],
    pricings: ["免费版", "Plus $7.99/月"],
    links: {},
    voteCount: 550,
    metaKeywords: ["Quizlet", "AI工具"],
    metaDescription: "Quizlet - AI工具",
    searchSuggestWords: ["quizlet"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-julius",
    userId: "00000000000000000",
    siteKey: "julius",
    url: "https://julius.ai",
    name: "Julius AI",
    icon: "mdi:chart-bar",
    subCategory: "数据分析",
    featured: true,
    weight: 71,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fjulius.ai?w=640",
    description: "AI 数据分析助手，通过自然语言即可分析数据、生成可视化图表和报告。",
    pricingType: "免费/付费",
    categories: ["AI数据分析", "AI办公"],
    images: [],
    features: ["自然语言分析", "图表生成", "多格式支持", "数据清洗", "报告生成"],
    usecases: ["数据分析", "可视化报告", "商业分析", "学术统计"],
    users: ["数据分析师", "研究人员", "学生", "商业分析师"],
    relatedSearches: ["Julius AI"],
    pricings: ["免费版", "Plus $20/月"],
    links: {},
    voteCount: 580,
    metaKeywords: ["Julius AI", "AI工具"],
    metaDescription: "Julius AI - AI工具",
    searchSuggestWords: ["julius"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-grammarly",
    userId: "00000000000000000",
    siteKey: "grammarly",
    url: "https://www.grammarly.com",
    name: "Grammarly",
    icon: "logos:grammarly",
    subCategory: "英文润色",
    featured: true,
    weight: 79,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.grammarly.com?w=640",
    description: "领先的 AI 英文写作助手，提供语法检查、润色建议、语气调整和抄袭检测。",
    pricingType: "免费/付费",
    categories: ["AI写作", "AI办公"],
    images: [],
    features: ["语法检查", "风格建议", "语气调整", "抄袭检测", "全平台集成"],
    usecases: ["英文写作", "邮件润色", "学术论文", "商业文档"],
    users: ["写作者", "学生", "职场人士", "非英语母语者"],
    relatedSearches: ["Grammarly"],
    pricings: ["免费版", "Premium $12/月"],
    links: {},
    voteCount: 700,
    metaKeywords: ["Grammarly", "AI工具"],
    metaDescription: "Grammarly - AI工具",
    searchSuggestWords: ["grammarly"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-writesonic",
    userId: "00000000000000000",
    siteKey: "writesonic",
    url: "https://writesonic.com",
    name: "Writesonic",
    icon: "mdi:pencil-box-outline",
    subCategory: "通用写作",
    featured: false,
    weight: 65,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwritesonic.com?w=640",
    description: "AI 内容创作平台，支持博客文章、广告文案、社交媒体内容等多种类型的文本生成。",
    pricingType: "免费/付费",
    categories: ["AI写作"],
    images: [],
    features: ["文章生成", "广告文案", "SEO优化", "多语言", "模板丰富"],
    usecases: ["博客写作", "营销文案", "社交媒体", "邮件营销"],
    users: ["内容营销人员", "博主", "电商运营"],
    relatedSearches: ["Writesonic"],
    pricings: ["免费试用", "Pro $16/月"],
    links: {},
    voteCount: 480,
    metaKeywords: ["Writesonic", "AI工具"],
    metaDescription: "Writesonic - AI工具",
    searchSuggestWords: ["writesonic"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-beautiful-ai",
    userId: "00000000000000000",
    siteKey: "beautiful-ai",
    url: "https://www.beautiful.ai",
    name: "Beautiful.ai",
    icon: "mdi:presentation",
    subCategory: "演示文档",
    featured: false,
    weight: 69,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.beautiful.ai?w=640",
    description: "AI 驱动的演示文稿工具，自动排版设计，让用户专注于内容而非样式。",
    pricingType: "免费/付费",
    categories: ["AI办公"],
    images: [],
    features: ["自动排版", "智能设计", "模板丰富", "团队协作", "品牌定制"],
    usecases: ["PPT制作", "商业演示", "项目提案", "工作报告"],
    users: ["职场人士", "创业者", "销售", "教育工作者"],
    relatedSearches: ["Beautiful.ai"],
    pricings: ["免费版", "Pro $12/月"],
    links: {},
    voteCount: 540,
    metaKeywords: ["Beautiful.ai", "AI工具"],
    metaDescription: "Beautiful.ai - AI工具",
    searchSuggestWords: ["beautiful-ai"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-chatpdf",
    userId: "00000000000000000",
    siteKey: "chatpdf",
    url: "https://www.chatpdf.com",
    name: "ChatPDF",
    icon: "mdi:file-document-outline",
    subCategory: "文档处理",
    featured: false,
    weight: 70,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.chatpdf.com?w=640",
    description: "AI 文档对话工具，上传 PDF 即可与文档对话、提取摘要、翻译内容。",
    pricingType: "免费/付费",
    categories: ["AI办公", "AI教育"],
    images: [],
    features: ["PDF对话", "摘要提取", "翻译", "多文档", "引用定位"],
    usecases: ["论文阅读", "合同分析", "报告审阅", "学习资料"],
    users: ["学生", "研究人员", "律师", "办公人员"],
    relatedSearches: ["ChatPDF"],
    pricings: ["免费版", "Plus $5/月"],
    links: {},
    voteCount: 610,
    metaKeywords: ["ChatPDF", "AI工具"],
    metaDescription: "ChatPDF - AI工具",
    searchSuggestWords: ["chatpdf"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-relay",
    userId: "00000000000000000",
    siteKey: "relay",
    url: "https://relay.app",
    name: "Relay.app",
    icon: "mdi:lightning-bolt-circle",
    subCategory: "工作流自动化",
    featured: false,
    weight: 62,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Frelay.app?w=640",
    description: "现代 AI 工作流自动化平台，连接各种应用和服务，通过 AI 增强的效率提高工作效率。",
    pricingType: "免费/付费",
    categories: ["AI自动化"],
    images: [],
    features: ["可视化工作流", "AI增强", "多应用集成", "条件逻辑", "团队协作"],
    usecases: ["自动化办公", "数据处理", "通知管理", "任务编排"],
    users: ["运营人员", "产品经理", "效率达人"],
    relatedSearches: ["Relay.app"],
    pricings: ["免费版", "Starter $10/月"],
    links: {},
    voteCount: 430,
    metaKeywords: ["Relay.app", "AI工具"],
    metaDescription: "Relay.app - AI工具",
    searchSuggestWords: ["relay"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-hubspot-ai",
    userId: "00000000000000000",
    siteKey: "hubspot-ai",
    url: "https://www.hubspot.com/products/crm/ai",
    name: "HubSpot AI",
    icon: "logos:hubspot",
    subCategory: "销售营销",
    featured: false,
    weight: 61,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.hubspot.com%2Fproducts%2Fcrm%2Fai?w=640",
    description: "HubSpot CRM 集成的 AI 功能，包括内容创作、销售预测、客户分析和智能回复。",
    pricingType: "免费/付费",
    categories: ["AI赚钱"],
    images: [],
    features: ["AI内容创作", "销售预测", "客户分析", "智能回复", "SEO优化"],
    usecases: ["营销自动化", "销售优化", "客户管理", "内容营销"],
    users: ["营销人员", "销售人员", "企业主"],
    relatedSearches: ["HubSpot AI", "CRM"],
    pricings: ["免费版", "Starter $20/月"],
    links: {},
    voteCount: 500,
    metaKeywords: ["HubSpot AI", "AI工具"],
    metaDescription: "HubSpot AI - AI工具",
    searchSuggestWords: ["hubspot-ai"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-apollo",
    userId: "00000000000000000",
    siteKey: "apollo",
    url: "https://www.apollo.io",
    name: "Apollo.io",
    icon: "mdi:rocket-launch-outline",
    subCategory: "销售营销",
    featured: false,
    weight: 58,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.apollo.io?w=640",
    description: "AI 驱动的销售智能平台，提供潜在客户挖掘、邮件自动化和数据 enrichment 等功能。",
    pricingType: "免费/付费",
    categories: ["AI赚钱"],
    images: [],
    features: ["客户挖掘", "邮件自动化", "数据分析", "序列销售", "CRM集成"],
    usecases: ["销售开发", "潜在客户挖掘", "邮件营销", "市场拓展"],
    users: ["销售人员", "商务拓展", "创业者"],
    relatedSearches: ["Apollo.io"],
    pricings: ["免费版", "Basic $49/月"],
    links: {},
    voteCount: 470,
    metaKeywords: ["Apollo.io", "AI工具"],
    metaDescription: "Apollo.io - AI工具",
    searchSuggestWords: ["apollo"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-allthingsai",
    userId: "00000000000000000",
    siteKey: "allthingsai",
    url: "https://allthingsai.com",
    name: "All Things AI",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 82,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fallthingsai.com?w=640",
    description: "AI 工具资源精选平台，收录各品类 AI 工具，提供分类浏览和搜索功能。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["All Things AI", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 820,
    metaKeywords: ["All Things AI", "AI工具目录", "AI导航"],
    metaDescription: "All Things AI - AI 工具目录导航站",
    searchSuggestWords: ["allthingsai", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-opentools",
    userId: "00000000000000000",
    siteKey: "opentools",
    url: "https://opentools.ai",
    name: "OpenTools",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 80,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fopentools.ai?w=640",
    description: "AI 工具发现平台，内置 GPT 聊天机器人，通过对话推荐适合你的 AI 工具。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["OpenTools", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 800,
    metaKeywords: ["OpenTools", "AI工具目录", "AI导航"],
    metaDescription: "OpenTools - AI 工具目录导航站",
    searchSuggestWords: ["opentools", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-thenextaitool",
    userId: "00000000000000000",
    siteKey: "thenextaitool",
    url: "https://thenextaitool.com",
    name: "The Next AI Tool",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 85,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fthenextaitool.com?w=640",
    description: "超大型 AI 工具目录，收录 43,000+ AI 工具，覆盖 80+ 分类，每日更新。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["The Next AI Tool", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 850,
    metaKeywords: ["The Next AI Tool", "AI工具目录", "AI导航"],
    metaDescription: "The Next AI Tool - AI 工具目录导航站",
    searchSuggestWords: ["thenextaitool", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-topai-tools",
    userId: "00000000000000000",
    siteKey: "topai-tools",
    url: "https://topai.tools",
    name: "TopAI.tools",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 78,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Ftopai.tools?w=640",
    description: "精选每日最佳 AI 工具，提供排行榜、分类浏览和用户评价功能。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["TopAI.tools", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 780,
    metaKeywords: ["TopAI.tools", "AI工具目录", "AI导航"],
    metaDescription: "TopAI.tools - AI 工具目录导航站",
    searchSuggestWords: ["topai-tools", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-aihubs",
    userId: "00000000000000000",
    siteKey: "aihubs",
    url: "https://aihubs.ai",
    name: "AI Hubs",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 74,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Faihubs.ai?w=640",
    description: "AI 工具目录聚合平台，帮你发现最新最强大的 AI 应用。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["AI Hubs", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 740,
    metaKeywords: ["AI Hubs", "AI工具目录", "AI导航"],
    metaDescription: "AI Hubs - AI 工具目录导航站",
    searchSuggestWords: ["aihubs", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-theailibrary",
    userId: "00000000000000000",
    siteKey: "theailibrary",
    url: "https://www.theailibrary.co",
    name: "AI Library",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 76,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.theailibrary.co?w=640",
    description: "收录 500+ AI 工具的强大目录，覆盖生产力到创意等各个领域。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["AI Library", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 760,
    metaKeywords: ["AI Library", "AI工具目录", "AI导航"],
    metaDescription: "AI Library - AI 工具目录导航站",
    searchSuggestWords: ["theailibrary", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-aihuntlist",
    userId: "00000000000000000",
    siteKey: "aihuntlist",
    url: "https://aihuntlist.com",
    name: "AI Hunt List",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 77,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Faihuntlist.com?w=640",
    description: "发现最佳 AI 产品和工具，3000+ AI 产品，200+ 分类。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["AI Hunt List", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 770,
    metaKeywords: ["AI Hunt List", "AI工具目录", "AI导航"],
    metaDescription: "AI Hunt List - AI 工具目录导航站",
    searchSuggestWords: ["aihuntlist", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-toolpilot",
    userId: "00000000000000000",
    siteKey: "toolpilot",
    url: "https://www.toolpilot.ai",
    name: "Tool Pilot",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 72,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.toolpilot.ai?w=640",
    description: "导航 AI 工具世界，提供智能化工具推荐和分类浏览。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["Tool Pilot", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 720,
    metaKeywords: ["Tool Pilot", "AI工具目录", "AI导航"],
    metaDescription: "Tool Pilot - AI 工具目录导航站",
    searchSuggestWords: ["toolpilot", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-toolfinder-wiki",
    userId: "00000000000000000",
    siteKey: "toolfinder-wiki",
    url: "https://toolfinder.wiki",
    name: "ToolFinder",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 70,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Ftoolfinder.wiki?w=640",
    description: "发现和浏览数千种工具，帮你找到最适合的 AI 解决方案。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["ToolFinder", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 700,
    metaKeywords: ["ToolFinder", "AI工具目录", "AI导航"],
    metaDescription: "ToolFinder - AI 工具目录导航站",
    searchSuggestWords: ["toolfinder-wiki", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-futurepedia-wiki",
    userId: "00000000000000000",
    siteKey: "futurepedia-wiki",
    url: "https://futurepedia.wiki",
    name: "Futurepedia Wiki",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 79,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Ffuturepedia.wiki?w=640",
    description: "寻找最前沿的 AI 工具，Futurepedia 的 Wiki 版本。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["Futurepedia Wiki", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 790,
    metaKeywords: ["Futurepedia Wiki", "AI工具目录", "AI导航"],
    metaDescription: "Futurepedia Wiki - AI 工具目录导航站",
    searchSuggestWords: ["futurepedia-wiki", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-orbic-ai",
    userId: "00000000000000000",
    siteKey: "orbic-ai",
    url: "https://orbic.ai",
    name: "Orbic AI",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 75,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Forbic.ai?w=640",
    description: "最大的 GPT Store 和 AI 工具目录，发现最新的 AI 应用和 GPT。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["Orbic AI", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 750,
    metaKeywords: ["Orbic AI", "AI工具目录", "AI导航"],
    metaDescription: "Orbic AI - AI 工具目录导航站",
    searchSuggestWords: ["orbic-ai", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-openfuture-ai",
    userId: "00000000000000000",
    siteKey: "openfuture-ai",
    url: "https://openfuture.ai",
    name: "OpenFuture AI",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 81,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fopenfuture.ai?w=640",
    description: "最大的 AI 工具目录，更新最快、数据库最准确的 AI 导航站。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["OpenFuture AI", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 810,
    metaKeywords: ["OpenFuture AI", "AI工具目录", "AI导航"],
    metaDescription: "OpenFuture AI - AI 工具目录导航站",
    searchSuggestWords: ["openfuture-ai", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-stackviv",
    userId: "00000000000000000",
    siteKey: "stackviv",
    url: "https://stackviv.ai",
    name: "Stackviv",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 73,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fstackviv.ai?w=640",
    description: "大型 AI 目录网站，跨越 1000+ 精选分类，收录最佳 AI 工具。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["Stackviv", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 730,
    metaKeywords: ["Stackviv", "AI工具目录", "AI导航"],
    metaDescription: "Stackviv - AI 工具目录导航站",
    searchSuggestWords: ["stackviv", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-neonrev",
    userId: "00000000000000000",
    siteKey: "neonrev",
    url: "https://www.neonrev.com",
    name: "NeonRev",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 71,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.neonrev.com?w=640",
    description: "最大最好的 AI 工具目录之一，提供全面的 AI 工具发现体验。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["NeonRev", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 710,
    metaKeywords: ["NeonRev", "AI工具目录", "AI导航"],
    metaDescription: "NeonRev - AI 工具目录导航站",
    searchSuggestWords: ["neonrev", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-aichief",
    userId: "00000000000000000",
    siteKey: "aichief",
    url: "https://aichief.com",
    name: "AIChief",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 76,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Faichief.com?w=640",
    description: "为企业、AI 探索者和好奇灵魂打造的 #1 AI 工具目录。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["AIChief", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 760,
    metaKeywords: ["AIChief", "AI工具目录", "AI导航"],
    metaDescription: "AIChief - AI 工具目录导航站",
    searchSuggestWords: ["aichief", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-aitoolshunt",
    userId: "00000000000000000",
    siteKey: "aitoolshunt",
    url: "https://aitoolshunt.com",
    name: "AIToolsHunt",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 69,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Faitoolshunt.com?w=640",
    description: "全面的 AI 工具目录，帮助发现最新的 AI 工具和应用。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["AIToolsHunt", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 690,
    metaKeywords: ["AIToolsHunt", "AI工具目录", "AI导航"],
    metaDescription: "AIToolsHunt - AI 工具目录导航站",
    searchSuggestWords: ["aitoolshunt", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-bestofai",
    userId: "00000000000000000",
    siteKey: "bestofai",
    url: "https://bestofai.io",
    name: "Best of AI",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 68,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fbestofai.io?w=640",
    description: "精选最佳 AI 工具列表，只收录真正优秀的 AI 产品。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["Best of AI", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 680,
    metaKeywords: ["Best of AI", "AI工具目录", "AI导航"],
    metaDescription: "Best of AI - AI 工具目录导航站",
    searchSuggestWords: ["bestofai", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-navtools-ai",
    userId: "00000000000000000",
    siteKey: "navtools-ai",
    url: "https://navtools.ai",
    name: "NavTools AI",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 72,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fnavtools.ai?w=640",
    description: "最佳 AI 工具目录和 AI 工具列表，提供高质量的 AI 导航服务。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["NavTools AI", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 720,
    metaKeywords: ["NavTools AI", "AI工具目录", "AI导航"],
    metaDescription: "NavTools AI - AI 工具目录导航站",
    searchSuggestWords: ["navtools-ai", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-alltheaitools",
    userId: "00000000000000000",
    siteKey: "alltheaitools",
    url: "https://alltheaitools.com",
    name: "All The AI Tools",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 70,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Falltheaitools.com?w=640",
    description: "全面的 AI 工具目录，支持比较和选择最适合需求的 AI 工具。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["All The AI Tools", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 700,
    metaKeywords: ["All The AI Tools", "AI工具目录", "AI导航"],
    metaDescription: "All The AI Tools - AI 工具目录导航站",
    searchSuggestWords: ["alltheaitools", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-aitooltrek",
    userId: "00000000000000000",
    siteKey: "aitooltrek",
    url: "https://aitooltrek.com",
    name: "AI Tool Trek",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 65,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Faitooltrek.com?w=640",
    description: "精选最新 AI 工具和 AI 新闻的策展平台。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["AI Tool Trek", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 650,
    metaKeywords: ["AI Tool Trek", "AI工具目录", "AI导航"],
    metaDescription: "AI Tool Trek - AI 工具目录导航站",
    searchSuggestWords: ["aitooltrek", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-thatsmyai",
    userId: "00000000000000000",
    siteKey: "thatsmyai",
    url: "https://thatsmy.ai",
    name: "ThatsMyAI",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 67,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fthatsmy.ai?w=640",
    description: "发现适合你需求的 AI 应用和认证，个性化推荐 AI 工具。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["ThatsMyAI", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 670,
    metaKeywords: ["ThatsMyAI", "AI工具目录", "AI导航"],
    metaDescription: "ThatsMyAI - AI 工具目录导航站",
    searchSuggestWords: ["thatsmyai", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-trustlist",
    userId: "00000000000000000",
    siteKey: "trustlist",
    url: "https://www.trustlist.ai",
    name: "TrustList",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 66,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.trustlist.ai?w=640",
    description: "可信赖的 AI 指南，发现能简化日常任务的 AI 解决方案。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["TrustList", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 660,
    metaKeywords: ["TrustList", "AI工具目录", "AI导航"],
    metaDescription: "TrustList - AI 工具目录导航站",
    searchSuggestWords: ["trustlist", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-toolwave",
    userId: "00000000000000000",
    siteKey: "toolwave",
    url: "https://www.toolwave.io",
    name: "Toolwave.io",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 64,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.toolwave.io?w=640",
    description: "发现数千种适用于各种场景的 AI 工具。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["Toolwave.io", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 640,
    metaKeywords: ["Toolwave.io", "AI工具目录", "AI导航"],
    metaDescription: "Toolwave.io - AI 工具目录导航站",
    searchSuggestWords: ["toolwave", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-whatsthebigdata",
    userId: "00000000000000000",
    siteKey: "whatsthebigdata",
    url: "https://whatsthebigdata.com/ai-tools",
    name: "WhatstheBigData.com",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 63,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwhatsthebigdata.com%2Fai-tools?w=640",
    description: "浏览顶级 AI 工具，提供 AI 工具的评测和比较。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["WhatstheBigData.com", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 630,
    metaKeywords: ["WhatstheBigData.com", "AI工具目录", "AI导航"],
    metaDescription: "WhatstheBigData.com - AI 工具目录导航站",
    searchSuggestWords: ["whatsthebigdata", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-aifordevelopers",
    userId: "00000000000000000",
    siteKey: "aifordevelopers",
    url: "https://aifordevelopers.org",
    name: "AI For Developers",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 74,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Faifordevelopers.org?w=640",
    description: "面向开发者的 AI 开发工具精选列表，帮助开发者找到最佳 AI DevTools。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["AI For Developers", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 740,
    metaKeywords: ["AI For Developers", "AI工具目录", "AI导航"],
    metaDescription: "AI For Developers - AI 工具目录导航站",
    searchSuggestWords: ["aifordevelopers", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "site-ainave",
    userId: "00000000000000000",
    siteKey: "ainave",
    url: "https://www.ainave.com",
    name: "ainave",
    icon: "mdi:compass-outline",
    subCategory: "AI目录导航",
    featured: false,
    weight: 62,
    snapshot: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.ainave.com?w=640",
    description: "轻松导航 AI 世界！提供简洁的 AI 工具发现体验。",
    pricingType: "免费",
    categories: ["AI目录导航"],
    images: [],
    features: ["分类浏览", "搜索功能", "AI工具收录", "每日更新"],
    usecases: ["发现AI工具", "工具对比", "了解AI趋势", "提交工具"],
    users: ["AI用户", "开发者", "创业者", "产品经理"],
    relatedSearches: ["ainave", "AI工具目录", "AI导航"],
    pricings: ["免费"],
    links: {},
    voteCount: 620,
    metaKeywords: ["ainave", "AI工具目录", "AI导航"],
    metaDescription: "ainave - AI 工具目录导航站",
    searchSuggestWords: ["ainave", "ai工具"],
    state: SiteState.published,
    processStage: ProcessStage.success,
    createdAt: now,
    updatedAt: now,
  },
];

export function getSeedFeaturedSites(size = 12): Site[] {
  return SEED_SITES.filter((s) => s.featured)
    .sort((a, b) => b.weight - a.weight)
    .slice(0, size);
}

export function getSeedLatestSites(size = 12): Site[] {
  return [...SEED_SITES]
    .sort((a, b) => b.updatedAt - a.updatedAt)
    .slice(0, size);
}

export function getSeedFeaturedCategories(): Category[] {
  return SEED_CATEGORIES.filter((c) => c.featured).sort(
    (a, b) => b.weight - a.weight,
  );
}

export function getSeedSiteByKey(siteKey: string): Site | undefined {
  return SEED_SITES.find((s) => s.siteKey === siteKey);
}


export function searchSeedSites({
  search,
  category,
  page,
  pricing = "all",
  rating = 0,
}: {
  search: string;
  category: string;
  page: number;
  pricing?: "all" | "free" | "paid";
  rating?: number;
}): { sites: Site[]; total: number } {
  const pageSize = 24;
  let filtered = SEED_SITES.filter((s) => s.state === SiteState.published);

  // Pricing filter
  if (pricing === "free") {
    filtered = filtered.filter((s) => s.pricingType?.includes("免费"));
  } else if (pricing === "paid") {
    filtered = filtered.filter((s) => !s.pricingType?.includes("免费"));
  }

  // Rating filter (skip for seed data as it doesn't have rating field)
  // TODO: Add rating field to seed data if needed

  if (category) {
    filtered = filtered.filter((s) =>
      s.categories.some((c) => c.includes(category)),
    );
  }

  if (search) {
    const q = search.toLowerCase();
    filtered = filtered.filter(
      (s) =>
        s.name.toLowerCase().includes(q) ||
        s.description.toLowerCase().includes(q) ||
        s.categories.some((c) => c.toLowerCase().includes(q)) ||
        s.searchSuggestWords.some((w) => w.toLowerCase().includes(q)),
    );
  }

  const total = filtered.length;
  const sites = filtered.slice((page - 1) * pageSize, page * pageSize);

  return { sites, total };
}
